# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[(b'male', b'\xe7\x94\xb7'), (b'female', b'\xe5\xa5\xb3')], default=b'male', max_length=20, null=True),
        ),
    ]
