# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180725_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='MyDiary',
        ),
    ]
