# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-25 07:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0003_auto_20180725_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(null=True, verbose_name=b'\xe9\xa2\x84\xe7\xae\x97')),
                ('weight', models.FloatField(null=True, verbose_name=b'\xe4\xbd\x93\xe9\x87\x8d')),
                ('note', models.TextField(null=True, verbose_name=b'\xe7\xac\x94\xe8\xae\xb0')),
                ('date', models.DateField(null=True, verbose_name=b'\xe6\x97\xa5\xe6\x9c\x9f')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
            ],
        ),
        migrations.RemoveField(
            model_name='mydiary',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyDiary',
        ),
    ]
